import { Button, List, ScrollArea, Stack, TextInput } from '@mantine/core';
import Head from 'next/head';
import { useState } from 'react';
import { api } from '~/utils/api';

export default function Home() {
  const [anime, setAnime] = useState('');
  const [fetchLinks, setFetchLinks] = useState(false);
  const [loading, setLoading] = useState(false);
  const { data: animeData } = api.scrape.getSite.useQuery(
    { anime },
    {
      enabled: fetchLinks,
      onSuccess() {
        setFetchLinks(false);
        setLoading(false);
      },
    }
  );

  const handleFetch = () => {
    setLoading(true);
    setFetchLinks(true);
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Stack>
          <h2>
            Enter Anime name from <a href='https://animeblkom.net/'>Anime Blkom</a>
          </h2>
          <TextInput value={anime} onChange={event => setAnime(event.currentTarget.value)} />;
          <Button type='button' loading={loading} onClick={handleFetch}>
            Submit
          </Button>
          <ScrollArea h={400}>
            <List type='ordered'>
              {animeData?.downloadLinks.map((downloadLink, idx) => (
                <List.Item key={idx}>{downloadLink}</List.Item>
              ))}
            </List>
          </ScrollArea>
        </Stack>
      </main>
    </>
  );
}

// export const getServerSideProps: GetServerSideProps = async () => {
//   const res = await fetch('https://api.github.com/repos/vercel/next.js');
//   const repo = await res.json();

//   return { props: { repo } };
// };
